---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gitpod-issuer
spec:
  acme:
    email: $LETSENCRYPT_EMAIL
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          azureDNS:
            subscriptionID: $AZURE_SUBSCRIPTION_ID
            resourceGroupName: $RESOURCE_GROUP
            hostedZoneName: $DOMAIN
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $CERT_NAME
spec:
  secretName: $CERT_NAME
  issuerRef:
    name: gitpod-issuer
    kind: ClusterIssuer
  dnsNames:
    - $DOMAIN
    - "*.$DOMAIN"
    - "*.ws.$DOMAIN"
